# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRect, QSize
from PyQt6.QtWidgets import QLayout, QSpacerItem, QLabel, QTextEdit, QHBoxLayout, QScrollArea, QPushButton


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        # CONFIG WINDOW
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)

        MainWindow.setStyleSheet("""
        
        QWidget{margin:0px; padding:0px;border-radius: 10px;  }
        QVBoxLayout{margin:0px; padding:0px; spacing: 0px;}
        QHBoxLayout{margin:0px; padding:0px; spacing: 0px;}
        QWidget { margin: 0px; padding: 0px; spacing: 0px;}
        #leftwidget {background-color: #D5E6FF}
        QMainWindow {margin: 0px; padding: 0px; spacing: 0px;}
        
        QPushButton{
        background-color: #5598FD;
        radius: 12px;
        font-family: Anonymous Pro;
        color: #ffffff;
font-style: Regular;
font-size: 14px;
letter-spacing: 0%;
}

        QTextEdit{
        background-color: #D5E6FF;
        radius:50px}""")

        # CREATE
        ## Widgets
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow) # main widget
        # self.centralwidget.setStyleSheet("background-color: green;")
        self.leftwidget = QtWidgets.QWidget(parent=self.centralwidget, objectName="leftwidget") # header widget
        self.rightwidget = QtWidgets.QWidget(parent=self.centralwidget) # right widget
        self.headerwidget = QtWidgets.QWidget(parent=self.rightwidget) # header widget
        self.mainwidget = QtWidgets.QWidget(parent=self.rightwidget) # main widget

        ## Layouts
        self.centerLayout = QtWidgets.QHBoxLayout(self.centralwidget) # horizontalLayout in centralwidget
        self.centerLayout.setContentsMargins(0, 0, 0, 0)

        self.leftLayout = QtWidgets.QVBoxLayout(self.leftwidget) # leftLayout in leftwidget
        # self.leftLayout.setContentsMargins(0, 0, 0, 0)

        self.rightLayout = QtWidgets.QVBoxLayout(self.rightwidget) # rightLayout in mainwidget
        self.rightLayout.setContentsMargins(0, 0, 0, 0)

        self.headerLayout = QtWidgets.QHBoxLayout(self.headerwidget) # headerLayout in headerwidget
        # self.headerLayout.setContentsMargins(0, 0, 0, 0)

        self.mainLayout = QtWidgets.QHBoxLayout(self.mainwidget) # mainLayout in mainwidget
        self.mainLayout.setContentsMargins(0, 0, 0, 0)

        # ADD TO LAYOUTS
        self.centerLayout.addWidget(self.leftwidget, 0) # left
        self.centerLayout.addWidget(self.rightwidget, 0) # main
        self.rightLayout.addWidget(self.headerwidget, 0) # head

        self.headerwinget_config()
        self.leftwidget_config()
        self.rightwidget_config()

        MainWindow.setCentralWidget(self.centralwidget)

    def headerwinget_config(self):
        self.headerwidget.setFixedHeight(50)
        # Search
        self.labelSearch = QTextEdit(self.headerwidget)
        self.labelSearch.setFixedWidth(400)
        self.headerLayout.addWidget(self.labelSearch)


        spacer = QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addSpacerItem(spacer)

        # Money
        self.labelMoney = QLabel("Balance: 10000", self.headerwidget)
        self.headerLayout.addWidget(self.labelMoney)

        # Bell
        self.labelBell = QLabel("Колокольчик", self.headerwidget)
        self.headerLayout.addWidget(self.labelBell)

        # Chats
        self.labelChats = QLabel("Chats", self.headerwidget)
        self.headerLayout.addWidget(self.labelChats)

        # Avatar
        self.lavelAvatar = QLabel("Avatar", self.headerwidget)
        self.headerLayout.addWidget(self.lavelAvatar)

    def leftwidget_config(self):
        self.leftwidget.setFixedWidth(75)

        # Home
        self.labelHome = QLabel("Home", self.leftwidget)
        self.leftLayout.addWidget(self.labelHome)

        # Spacer
        spacer = QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        self.leftLayout.addSpacerItem(spacer)

        # Games
        self.labelGames = QPushButton("Games", self.leftwidget)
        self.leftLayout.addWidget(self.labelGames)

        # Studios
        self.labelStudios = QPushButton("Studios", self.leftwidget)
        self.leftLayout.addWidget(self.labelStudios)

        # Friends
        self.labelFriends = QPushButton("Friends", self.leftwidget)
        self.leftLayout.addWidget(self.labelFriends)

        # Spacer
        self.leftLayout.addSpacerItem(spacer)

        # Settings
        self.labelSettings = QLabel("Settings", self.leftwidget)
        self.leftLayout.addWidget(self.labelSettings)

    def rightwidget_config(self):
        self.recently_widget = QtWidgets.QWidget()
        self.recently_layout = QHBoxLayout(self.recently_widget)
        self.recently_scroll = QScrollArea()

        for i in range(10):
            self.create_card(self.recently_layout, "1")

        self.rightLayout.addWidget(self.recently_scroll)
        self.recently_scroll.setWidget(self.recently_widget) # must be after add to cart
        self.recently_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        # ============================

        self.popular_widget = QtWidgets.QWidget()
        self.popular_layout = QHBoxLayout(self.popular_widget)
        self.popular_scroll = QScrollArea()

        for i in range(10):
            self.create_card(self.popular_layout, "1")

        self.rightLayout.addWidget(self.popular_scroll)
        self.popular_scroll.setWidget(self.popular_widget)  # must be after add to cart
        self.popular_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        # =============================

        self.all_games_widget = QtWidgets.QWidget()
        self.all_games_layout = QHBoxLayout(self.all_games_widget)
        self.all_games_scroll = QScrollArea()

        for i in range(10):
            self.create_card(self.all_games_layout, "1") # add cart

        self.rightLayout.addWidget(self.all_games_scroll)
        self.all_games_scroll.setWidget(self.all_games_widget)  # must be after add to cart
        self.all_games_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)



    def create_card(self, layout, name):
        widget = QtWidgets.QWidget(self.rightwidget, objectName=name)
        widget.setStyleSheet("background-color: #bbbbbb")
        widget.setFixedWidth(200)
        widget.setFixedHeight(100)
        layout.addWidget(widget)